# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ar_email',
        ),
    ]
