# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0005_auto_20170325_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='painting',
            field=models.ImageField(default=b'paintings/None/no-img.jpg', upload_to=b'paintings/'),
        ),
    ]
