# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0006_auto_20170325_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
