# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0007_auto_20170328_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default=b'documents/None/no-img.jpg', upload_to=b'documents/'),
        ),
    ]
